### ISSUE TITLE
feat: Integrate an LLM in the form builder playground

### ISSUE THREAD

**Issue by techsavvyash** [techsavvyash/bhasai-form-builder#30]
## Description

Add an LLM in the form builder react app, which gives auto complete suggestions, verbose descriptions etc. to help the users have a better experience and speed up their form building journey.

## Tasks

- [ ] Figure out a list of things to be supported by the LLM in the first version - @techsavvyash 
- [ ] Figure out good ways/strategies to integrate an LLM in the playground - @Debatreya 
- [ ] Integrate the LLM - @Debatreya
