### ISSUE TITLE
feat: allow for API calls in validators

### ISSUE THREAD

**Issue by techsavvyash** [techsavvyash/bhasai-form-builder#34]
## Description

Right now we only have 2 types of validators - AI-based (LLMs) and Non-AI-based (regex-based). We want to expand the list for non-AI-based and include some validators that call some API internally (possibly via using `HTTP GET` and `HTTP POST` transformers).

## Tasks

- [ ] Design how to support these validators
    - [ ] How to accept API Call parameters
    - [ ] How to accept API response manipulation logic 
- [ ] Design how to allow for these API-based validators to be intermingled with regex-based validators
