### ISSUE TITLE
feat: allow for grouping fields together/section

### ISSUE THREAD

**Issue by techsavvyash** [techsavvyash/bhasai-form-builder#36]
## Description

There might be use cases where the user wants to group related fields together, or break the form down into different sections, hence this needs to be supported.

## Possible Solution

The code formily platform supports `Object` as a input object which helps club items together and these clubbed items act as a composite item which can be a good feature to have.

## Tasks

- [ ] Design the feature
    - [ ] should allow for manipulating the fields grouped using  `object` separately (because we would need to parse the JSON to create a flow or have specific requirement for individual fields)
    - [ ] should allow for manipulated the grouped object as a whole for properties common across all (for example #35 )
- [ ] Implement the feature
